apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  CATALOG_SERVICE_URL: "http://catalog-service:8081"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=8442d4fe-bd6d-4d06-afd4-f7dfef0a2697"