apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ecommercereglokashakhivelsp.azurecr.io/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: CATALOG_URL
              value: "http://catalog-service:8081"
            - name: CART_URL
              value: "http://cart-service:8082"
            - name: ORDER_URL
              value: "http://order-service:8083"
            - name: USER_URL
              value: "http://user-service:8084"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000