apiVersion: v1
kind: Service
metadata:
  name: catalog-service-external
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-external
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-external
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-external
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # This annotation is mandatory to strip the /api/ prefix
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # The regex (products.*) captures everything after /api/ into $1
          - path: /api/(products.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-service-external
                port:
                  number: 8081
          - path: /api/(cart.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cart-service-external
                port:
                  number: 8082
          - path: /api/(orders.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service-external
                port:
                  number: 8083
          - path: /api/(auth.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service-external
                port:
                  number: 8084
          - path: /api/(users.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service-external
                port:
                  number: 8084
          # Catch-all for your Next.js frontend UI
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-external
                port:
                  number: 3000