server.port=8083
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://postgres:5432/orderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

catalog.service.url=http://catalog-service:8081